### PR TITLE
Avoid asserting when the WebSocket server could not be created

### LINKED ISSUE #83: Assertion firing when port already occupied
Whenever binding the TCP port for the Websocket server fails, the `Remotery_Constructor` returns w/ an error code before having set the `g_Remotery`/`g_RemoteryCreated` globals.

As the `EndNew` macro calls `Remotery_Destructor` automatically on error, it will fire the assertions that begin that function:

```
assert(g_RemoteryCreated == RMT_TRUE)
```

My proposed fix would be to move the assertions into `rmt_DestroyGlobalInstance` and in the destructor erase g_Remotery if and only if g_RemoteryCreated is true

### PR DESCRIPTION
**Pull request by nil-ableton**
This fixes #83

If for instance the port is already occupied, `Remotery_Constructor`
will return with an error before g_Remotery and g_RemoteryCreated could
be set.

This situation triggers an assertion immediately in `Remotery_Destructor`
since it expects these globals to have been set.

This fixes it by asserting only when coming from the intended API entry
point, `rmt_DestroyGlobalInstance` which is where the assertion would be
most useful.

### CODE REVIEW

File: lib/Remotery.c [hunk 1]
```diff
@@ -4233,11 +4233,11 @@ static void Remotery_Destructor(Remotery* rmt)
...
-    // Ensure this is the module that created it
-    assert(g_RemoteryCreated == RMT_TRUE);
-    assert(g_Remotery == rmt);
-    g_Remotery = NULL;
-    g_RemoteryCreated = RMT_FALSE;
+    if (g_RemoteryCreated)
+    {
+      g_Remotery = NULL;
+      g_RemoteryCreated = RMT_FALSE;
+    }
```
Comment (dwilliamson) [inline lib/Remotery.c]: I'm looking at the code and it doesn't look like the `if (g_RemoteryCreated)` check is needed:

- If `g_RemoteryCreated == RMT_FALSE` then there is no harm in setting it to `RMT_FALSE` anyway.
- When `g_RemoteryCreated == RM_FALSE` and `g_Remotery` is a valid pointer (from `rmt_SetGlobalInstance`), the destructor will never be called as the assert below would trap it before then.

Does that make sense?

Comment (nil-ableton) [inline lib/Remotery.c]: Yes that makes sense.

I wrote it in this way to mimick the New() .. Delete(...) pattern which is used for other aspects of the remotery instance to deal with conditional destruction of a constructed part.

I.e. the pattern that Delete(...) follows of destructing iff the object is not null

Comment (dwilliamson) [inline lib/Remotery.c]: Right. The "assign to global pointer" pattern is broken in there anyway and doesn't really adhere to the New/Delete lifetime pattern (`Remotery_ThreadMain` needs to be created outside the Remotery constructor). But there is value in bringing it closer.

**Comment by dwilliamson** [comment]
Thanks for fixing this.

**Comment by nil-ableton** [comment]
Thanks your quick feedback!
